---
version: "3.9"

services:
  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    ports:
      - 8080:8080

  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    environment:
      # set based on your imported database
      POSTGRES_DB: elahe
      # set based on your imported database username
      POSTGRES_USER: elahe
      POSTGRES_PASSWORD: elahe
    ports:
      - 5432:5432
    volumes:
      - ./output.sql:/docker-entrypoint-initdb.d/output.sql
